# Generated by Django 6.0.5 on 2026-06-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes',
            new_name='Ingrediente',
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Pizzas'},
        ),
    ]
